<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>

	<ItemGroup>
		<!-- NuGet Packages -->
		<PackageReference Include="coverlet.collector" Version="6.0.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
		<PackageReference Include="Microsoft.PowerPlatform.Dataverse.Client" Version="1.2.9" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="Pose" Version="1.2.1" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CCH.HPSO.Azure.EmailTextGenerationApp\CCH.HPSO.Azure.EmailTextGenerationApp.csproj" />
		<ProjectReference Include="..\CCH.HPSO.Azure.EvaluateAndPublishApp\CCH.HPSO.Azure.EvaluateAndPublishApp.csproj" />
		<ProjectReference Include="..\CCH.HPSO.Azure.PromptGenerationApp\CCH.HPSO.Azure.PromptGenerationApp.csproj" />
		<ProjectReference Include="..\CCH.HPSO.Azure.Shared\CCH.HPSO.Azure.Shared.csproj" />
	</ItemGroup>
</Project>