using CCH.HPSO.Azure.Shared.DataModel;
using CCH.HPSO.Azure.Shared.Enum;

namespace CCH.HPSO.Azure.Shared.Contracts
{
    /// <summary>
    /// This interface defines a service for interacting with Azure OpenAI.
    /// </summary>
    public interface IOpenAIService
    {
        /// <summary>
        /// This method calls the Azure OpenAI service to generate text based on the provided prompt.
        /// </summary>
        /// <param name="inputMessage">The input message to be sent to AOAI</param>
        /// <returns>The text generated by AOAI for preview purpose</returns>
        Task<string> CallAzureOpenAIAsync(InputMessage inputMessage);
    }
}
