using CCH.HPSO.Azure.Shared.Contracts;
using CCH.HPSO.Azure.Shared.DataModel;
using CCH.HPSO.Azure.Shared.Enum;
using Microsoft.Extensions.Logging;
using System.Text;
using System.Text.Json;

namespace CCH.HPSO.Azure.Shared.Services
{
    /// <summary>
    /// This class defines a service for interacting with Azure OpenAI.
    /// </summary>
    public class OpenAIService : IOpenAIService
    {
        /// <summary>
        /// This property holds the logger instance used for logging information and errors.
        /// </summary>
        public ILogger _logger { get; set; }

        /// <summary>
        /// This constructor initializes the OpenAIService class with a logger instance.
        /// </summary>
        public OpenAIService()
        {
            _logger = new LoggerFactory().CreateLogger<OpenAIService>();
        }

        /// <summary>
        /// This method calls the Azure OpenAI service to generate text based on the provided prompt.
        /// </summary>
        /// <param name="inputMessage">The input message to be sent to AOAI</param>
        /// <param name="failureStageEnum">The failure stage enum to indicate the stage of failure</param>
        /// <returns>The text generated by AOAI for preview purpose</returns>
        public async Task<string> CallAzureOpenAIAsync(InputMessage inputMessage)
        {
            try
            {
                _logger.LogInformation("CallAzureOpenAIAsync method called");

                // Async method to get a chat completion from Azure OpenAI with specified language and professional tone
                // Get the OpenAI endpoint, API key, and deployment name from environment variables
                var endpoint = Environment.GetEnvironmentVariable("AOAI_Endpoint");
                var apiKey = Environment.GetEnvironmentVariable("AOAI_ApiKey");

                var handler = new HttpClientHandler();

                // Create the HTTP client using the custom handler
                using var httpClient = new HttpClient(handler);

                // Add the API key to the request headers
                httpClient.DefaultRequestHeaders.Add("api-key", apiKey);

                // Resolve the system message from the configurable value fetched from Dataverse (prompt template),
                // substituting the {PromptLanguage} and {Tone} tokens. Falls back to the built-in default when the
                // prompt template does not have a system message configured.
                string systemMessage = BuildSystemMessage(inputMessage);

                // Build the request body with the message list and temperature setting
                var requestBody = new
                {
                    messages = new[]
                    {
                         new { role = "system", content = systemMessage },
                         new { role = "user", content = inputMessage.PromptText }
                    }
                    //,temperature = 0
                };

                // Serialize the request body to JSON and set content type to application/json
                var content = new StringContent(JsonSerializer.Serialize(requestBody), Encoding.UTF8, "application/json");

                //var openAIEndpoint = $"{endpoint}/openai/deployments/{inputMessage.PromptDeploymentName}/chat/completions?api-version={inputMessage.PromptAppVersion}";
                var openAIEndpoint = Environment.GetEnvironmentVariable("AzureOpenAI");

                _logger.LogInformation("Sending request to OpenAI endpoint: {Endpoint}", openAIEndpoint);

                // Send POST request to Azure OpenAI chat completions endpoint
                var response = await httpClient.PostAsync(openAIEndpoint, content);

                // Throw an exception if the response indicates failure (non-2xx status code)
                response.EnsureSuccessStatusCode();

                // Read the response JSON string
                var responseString = await response.Content.ReadAsStringAsync();

                // Parse the JSON response
                using var doc = JsonDocument.Parse(responseString);

                // Extract the assistant's reply from the response JSON
                var completion = doc.RootElement
                                    .GetProperty("choices")[0]
                                    .GetProperty("message")
                                    .GetProperty("content")
                                    .GetString();

                // If completion is not null or whitespace, attempt to trim Markdown formatting
                if (!string.IsNullOrWhiteSpace(completion))
                {
                    // Find the first newline and last triple backtick to isolate main content
                    int firstNewline = completion.IndexOf('\n');
                    int lastBacktick = completion.LastIndexOf("```");

                    // If both markers are found and in correct order, extract the trimmed content
                    if (firstNewline != -1 && lastBacktick != -1 && lastBacktick > firstNewline)
                    {
                        completion = completion.Substring(firstNewline + 1, lastBacktick - firstNewline - 1).Trim();
                    }

                    // Return the cleaned-up content
                    return completion;
                }

                // If no valid content was found, return an empty string
                return string.Empty;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error calling Azure OpenAI: {Message}", ex.Message);
                throw;
            }
        }

        /// <summary>
        /// Builds the system message sent to Azure OpenAI. Uses the configurable system message carried on the
        /// input message (fetched from the prompt template in Dataverse) when present, otherwise falls back to the
        /// built-in default. The {PromptLanguage} and {Tone} tokens are substituted with the input message values.
        /// </summary>
        /// <param name="inputMessage">The input message containing the configurable system message and token values.</param>
        /// <returns>The resolved system message with tokens substituted.</returns>
        private static string BuildSystemMessage(InputMessage inputMessage)
        {
            string template = string.IsNullOrWhiteSpace(inputMessage.SystemMessage)
                ? DefaultSystemMessageTemplate
                : inputMessage.SystemMessage;

            return template
                .Replace("{PromptLanguage}", inputMessage.PromptLanguage ?? string.Empty)
                .Replace("{Tone}", inputMessage.Tone ?? string.Empty);
        }

        /// <summary>
        /// The built-in fallback system message template used when the prompt template in Dataverse does not
        /// have a system message configured. Contains the {PromptLanguage} and {Tone} tokens.
        /// </summary>
        private const string DefaultSystemMessageTemplate = "You are a B2B marketing expert fluent in English and {PromptLanguage}, working with retail outlets and stores. Your job is to write hyper-personalized marketing emails for business decision-makers using the store’s name, type, location, and a product recommendation. Use a {Tone} tone in your response. Write the email in {PromptLanguage} and use the local tone of {PromptLanguage} suitable for B2B communication for enterprise buyers. Use natural-sounding, industry-appropriate {PromptLanguage} phrasing, and culturally adopted expressions in {PromptLanguage} — not overly literal translations from English. Follow standard {PromptLanguage} email etiquette (professional, polite, not overly casual). Include a localized call-to-action (CTA) that fits the local tone of {PromptLanguage}.";
    }
}
